apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-agent-rca
  namespace: genai
spec:
  # Run every 5 minutes
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ai-agent
            image: arjunachari12/ai-agent:1.0.0
            imagePullPolicy: IfNotPresent
            env:
            # We connect to the MCP server deployed in Module 9
            - name: MCP_SERVER_URL
              value: "http://mcp-server-svc.genai.svc.cluster.local:80/sse"
            # Students must supply their API key via a Secret or direct env var
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: apiKey
                  optional: true
          restartPolicy: OnFailure
